In [14]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [2]:
#create dataframes from csv files

peptides = pd.read_csv("PD-datasets/train_peptides.csv")
proteins = pd.read_csv("PD-datasets/train_proteins.csv")
clinical = pd.read_csv("PD-datasets/train_clinical_data.csv")

In [3]:
pep_pivot = peptides.pivot(index="visit_id",columns="Peptide",values="PeptideAbundance").sort_values(by="visit_id")

In [4]:
pro_pivot = proteins.pivot(index="visit_id",columns="UniProt",values="NPX")

In [5]:
merged_pivots = pep_pivot.merge(pro_pivot,how='left',on='visit_id')
print(merged_pivots.shape)
merged_pivots.head()

(1113, 1195)


AADDTWEPFASGK  AAFGQGSGPIMLDEVQC(UniMod_4)TGTEASLADC(UniMod_4)K  \
visit_id                                                                    
10053_0       6580710.0                                           31204.4   
10053_12      6333510.0                                           52277.6   
10053_18      7129640.0                                           61522.0   
10138_12      7404780.0                                           46107.2   
10138_24     13788300.0                                           56910.3   

          AAFTEC(UniMod_4)C(UniMod_4)QAADK  AANEVSSADVK  \
visit_id                                                  
10053_0                          7735070.0          NaN   
10053_12                         5394390.0          NaN   
10053_18                         7011920.0      35984.7   
10138_12                        10610900.0          NaN   
10138_24                         6906160.0      13785.5   

          AATGEC(UniMod_4)TATVGKR  AATVGSLAGQPLQER  AAVYHHFISDGVR  \
visit_id                                                            
10053_0                       NaN              NaN        46620.3   
10053_12                      NaN              NaN        57554.5   
10053_18                  17188.0          19787.3        36029.4   
10138_12                  20910.2          66662.3        55253.9   
10138_24                  11004.2          63672.7        36819.8   

          ADDKETC(UniMod_4)FAEEGK  ADDKETC(UniMod_4)FAEEGKK  \
visit_id                                                      
10053_0                  236144.0                       NaN   
10053_12                 108298.0                   45885.4   
10053_18                 708729.0                 5067790.0   
10138_12                  79575.5                 6201210.0   
10138_24                  34160.9                 2117430.0   

          ADDLGKGGNEESTKTGNAGSR  ...    Q9HDC9    Q9NQ79    Q9NYU2   Q9UBR2  \
visit_id                         ...                                          
10053_0                     NaN  ...       NaN   9469.45   94237.6      NaN   
10053_12                    NaN  ...       NaN  14408.40       NaN      NaN   
10053_18                30838.2  ...  317477.0  38667.20  111107.0      NaN   
10138_12                26720.0  ...  557904.0  44556.90  155619.0  14647.9   
10138_24                15645.2  ...       NaN  47836.70  177619.0  17061.1   

           Q9UBX5    Q9UHG2    Q9UKV8   Q9UNU6    Q9Y646    Q9Y6R7  
visit_id                                                            
10053_0   23016.0  177983.0   65900.0  15382.0       NaN  19017.40  
10053_12  28537.0  171733.0   65668.1      NaN   9295.65  25697.80  
10053_18  37932.6  245188.0   59986.1  10813.3       NaN  29102.70  
10138_12  36927.7  229232.0  106564.0  26077.7  21441.80   7642.42  
10138_24  25510.4  176722.0   59471.4  12639.2  15091.40   6168.55  

[5 rows x 1195 columns]

In [6]:
full_merge = merged_pivots.merge(clinical,how='left',on='visit_id')
print(full_merge.shape)
full_merge.head()

(1113, 1203)


visit_id  AADDTWEPFASGK  AAFGQGSGPIMLDEVQC(UniMod_4)TGTEASLADC(UniMod_4)K  \
0   10053_0      6580710.0                                           31204.4   
1  10053_12      6333510.0                                           52277.6   
2  10053_18      7129640.0                                           61522.0   
3  10138_12      7404780.0                                           46107.2   
4  10138_24     13788300.0                                           56910.3   

   AAFTEC(UniMod_4)C(UniMod_4)QAADK  AANEVSSADVK  AATGEC(UniMod_4)TATVGKR  \
0                         7735070.0          NaN                      NaN   
1                         5394390.0          NaN                      NaN   
2                         7011920.0      35984.7                  17188.0   
3                        10610900.0          NaN                  20910.2   
4                         6906160.0      13785.5                  11004.2   

   AATVGSLAGQPLQER  AAVYHHFISDGVR  ADDKETC(UniMod_4)FAEEGK  \
0              NaN        46620.3                 236144.0   
1              NaN        57554.5                 108298.0   
2          19787.3        36029.4                 708729.0   
3          66662.3        55253.9                  79575.5   
4          63672.7        36819.8                  34160.9   

   ADDKETC(UniMod_4)FAEEGKK  ...   Q9UNU6    Q9Y646    Q9Y6R7  patient_id  \
0                       NaN  ...  15382.0       NaN  19017.40     10053.0   
1                   45885.4  ...      NaN   9295.65  25697.80     10053.0   
2                 5067790.0  ...  10813.3       NaN  29102.70     10053.0   
3                 6201210.0  ...  26077.7  21441.80   7642.42     10138.0   
4                 2117430.0  ...  12639.2  15091.40   6168.55     10138.0   

   visit_month  updrs_1  updrs_2  updrs_3  updrs_4  \
0          0.0      3.0      0.0     13.0      0.0   
1         12.0      4.0      2.0      8.0      0.0   
2         18.0      2.0      2.0      0.0      0.0   
3         12.0      3.0      6.0     31.0      0.0   
4         24.0      4.0      7.0     19.0     10.0   

   upd23b_clinical_state_on_medication  
0                                  NaN  
1                                  NaN  
2                                  NaN  
3                                   On  
4                                   On  

[5 rows x 1203 columns]

In [9]:
le = LabelEncoder()
encoded_mm = full_merge[["upd23b_clinical_state_on_medication"]].apply(le.fit_transform)
full_merge["upd23b_clinical_state_on_medication"] = encoded_mm["upd23b_clinical_state_on_medication"]
full_merge.head()

visit_id  AADDTWEPFASGK  AAFGQGSGPIMLDEVQC(UniMod_4)TGTEASLADC(UniMod_4)K  \
0   10053_0      6580710.0                                           31204.4   
1  10053_12      6333510.0                                           52277.6   
2  10053_18      7129640.0                                           61522.0   
3  10138_12      7404780.0                                           46107.2   
4  10138_24     13788300.0                                           56910.3   

   AAFTEC(UniMod_4)C(UniMod_4)QAADK  AANEVSSADVK  AATGEC(UniMod_4)TATVGKR  \
0                         7735070.0          NaN                      NaN   
1                         5394390.0          NaN                      NaN   
2                         7011920.0      35984.7                  17188.0   
3                        10610900.0          NaN                  20910.2   
4                         6906160.0      13785.5                  11004.2   

   AATVGSLAGQPLQER  AAVYHHFISDGVR  ADDKETC(UniMod_4)FAEEGK  \
0              NaN        46620.3                 236144.0   
1              NaN        57554.5                 108298.0   
2          19787.3        36029.4                 708729.0   
3          66662.3        55253.9                  79575.5   
4          63672.7        36819.8                  34160.9   

   ADDKETC(UniMod_4)FAEEGKK  ...   Q9UNU6    Q9Y646    Q9Y6R7  patient_id  \
0                       NaN  ...  15382.0       NaN  19017.40     10053.0   
1                   45885.4  ...      NaN   9295.65  25697.80     10053.0   
2                 5067790.0  ...  10813.3       NaN  29102.70     10053.0   
3                 6201210.0  ...  26077.7  21441.80   7642.42     10138.0   
4                 2117430.0  ...  12639.2  15091.40   6168.55     10138.0   

   visit_month  updrs_1  updrs_2  updrs_3  updrs_4  \
0          0.0      3.0      0.0     13.0      0.0   
1         12.0      4.0      2.0      8.0      0.0   
2         18.0      2.0      2.0      0.0      0.0   
3         12.0      3.0      6.0     31.0      0.0   
4         24.0      4.0      7.0     19.0     10.0   

   upd23b_clinical_state_on_medication  
0                                    2  
1                                    2  
2                                    2  
3                                    1  
4                                    1  

[5 rows x 1203 columns]

In [13]:
clean_df = full_merge[full_merge.upd23b_clinical_state_on_medication != 2]
clean_df = clean_df.fillna(0)
clean_df.set_index("visit_id")

AADDTWEPFASGK  AAFGQGSGPIMLDEVQC(UniMod_4)TGTEASLADC(UniMod_4)K  \
visit_id                                                                    
10138_12      7404780.0                                           46107.2   
10138_24     13788300.0                                           56910.3   
10138_36      6924040.0                                           64313.5   
10541_60      5578010.0                                           61435.3   
10541_84      4339140.0                                           18940.0   
...                 ...                                               ...   
8344_24       7254380.0                                           39743.8   
8344_54       5100900.0                                           56068.0   
8699_0        8855120.0                                           48152.5   
8699_12       6329690.0                                           42876.3   
8699_24       6312970.0                                           44462.7   

          AAFTEC(UniMod_4)C(UniMod_4)QAADK  AANEVSSADVK  \
visit_id                                                  
10138_12                        10610900.0          0.0   
10138_24                         6906160.0      13785.5   
10138_36                         9098610.0      26400.9   
10541_60                         4902210.0          0.0   
10541_84                         4370350.0      26725.7   
...                                    ...          ...   
8344_24                          8185820.0      19223.4   
8344_54                          6961010.0      17759.7   
8699_0                          11474200.0      19046.3   
8699_12                         11385900.0      14161.3   
8699_24                         12455000.0      11051.3   

          AATGEC(UniMod_4)TATVGKR  AATVGSLAGQPLQER  AAVYHHFISDGVR  \
visit_id                                                            
10138_12                 20910.20          66662.3        55253.9   
10138_24                 11004.20          63672.7        36819.8   
10138_36                 18784.60          78724.1        50155.8   
10541_60                 11377.50         107775.0        40710.1   
10541_84                  8668.14          94758.2        36451.5   
...                           ...              ...            ...   
8344_24                  17588.80          11032.0        36362.1   
8344_54                  16119.30          41213.9        36615.7   
8699_0                   11986.50          26279.5        43510.1   
8699_12                  14296.50          26175.0        33375.1   
8699_24                   1163.18          43279.8        67743.5   

          ADDKETC(UniMod_4)FAEEGK  ADDKETC(UniMod_4)FAEEGKK  \
visit_id                                                      
10138_12                  79575.5                 6201210.0   
10138_24                  34160.9                 2117430.0   
10138_36                 508579.0                 5601500.0   
10541_60                 330576.0                 2868310.0   
10541_84                 325450.0                 2418020.0   
...                           ...                       ...   
8344_24                  503480.0                 6437940.0   
8344_54                  340763.0                 5247830.0   
8699_0                   529311.0                 5224130.0   
8699_12                  361000.0                 4597960.0   
8699_24                  325328.0                 4666550.0   

          ADDLGKGGNEESTKTGNAGSR  ...   Q9UNU6   Q9Y646    Q9Y6R7  patient_id  \
visit_id                         ...                                           
10138_12                26720.0  ...  26077.7  21441.8   7642.42     10138.0   
10138_24                15645.2  ...  12639.2  15091.4   6168.55     10138.0   
10138_36                27798.6  ...      0.0  22910.5   9596.48     10138.0   
10541_60                33646.7  ...      0.0  23121.7  17482.50     10541.0   
10541_84                29388.1  ...      

In [ ]:
>>> import numpy as np
>>> from sklearn.linear_model import LinearRegression
>>> X = np.array([[1, 1], [1, 2], [2, 2], [2, 3]])
>>> # y = 1 * x_0 + 2 * x_1 + 3
>>> y = np.dot(X, np.array([1, 2])) + 3
>>> reg = LinearRegression().fit(X, y)
>>> reg.score(X, y)
1.0
>>> reg.coef_
array([1., 2.])
>>> reg.intercept_
3.0...
>>> reg.predict(np.array([[3, 5]]))
array([16.])

In [22]:
y = clean_df["updrs_3"]
X = clean_df.drop(["updrs_1","updrs_2","updrs_3","updrs_4"],axis=1)
reg = LinearRegression().fit(X, y)

In [24]:
reg.score(X, y)

1.0

In [25]:
reg.coef_

array([ 3.14921462e-08, -2.40192017e-06,  2.26627846e-05, ...,
        1.67550002e-05,  8.49013530e-08, -2.61020190e-09])

In [26]:
reg.intercept_

10.543580615725407

In [ ]:
reg.predict(